# Lokaler Build aus dem Quellcode:
#   docker compose -f docker-compose.build.yml up -d --build

services:
  haproxy-gui:
    build: .
    container_name: haproxy-gui
    restart: unless-stopped
    ports:
      - "8080:8080"   # Web-GUI
      - "80:80"       # optional: eingebetteter HAProxy
      - "443:443"     # optional: eingebetteter HAProxy
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: change-me        # unbedingt ändern!
      ENABLE_LOCAL_HAPROXY: "true"     # eingebetteten HAProxy-Cluster "Local" aktivieren
      # GUI_PORT: "8080"
      # SSH_TCP_MAXSEG: "1024"          # Linux-Standard für ausgehendes SSH; "0" deaktiviert die Begrenzung
      # Nach Änderungen neu bauen/erstellen: docker compose -f docker-compose.build.yml up -d --build --force-recreate
    volumes:
      - haproxy-gui-data:/data

volumes:
  haproxy-gui-data:
